server:
  port: 8081

spring:
  application:
    name: rideshare
  data:
    mongodb:
      uri: mongodb://localhost:27017/rideshare_db
  main:
    allow-bean-definition-overriding: true

jwt:
  secret: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"
  expiration: 86400000

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
  group-configs:
    - group: 'auth'
      display-name: 'Authentication APIs'
      paths-to-match: '/api/auth/**'
    - group: 'v1'
      display-name: 'V1 APIs'
      paths-to-match: '/api/v1/**'
    - group: 'core-rides'
      display-name: 'Core Ride APIs'
      paths-to-match: '/api/rides/**'
    - group: 'core-analytics'
      display-name: 'Core Analytics APIs'
      paths-to-match: '/api/analytics/**'
